[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]
readme = "README.md"
# license = "MIT"  # https://spdx.org/licenses/
# categories = [] # https://crates.io/category_slugs
# keywords = [] # free text


[dependencies]
anyhow = "~1.0"
itertools = "~0.10"
derive_builder = "~0.11"
lazy_static = "~1.4"
structopt = "~0.3"
log = "~0.4"
env_logger = "~0.9"
[dev-dependencies]
pretty_assertions = "~1.2"
